read:
  url: "https://raw.githubusercontent.com/giuliano-macedo/geodata-br-states/refs/heads/main/geojson/br_states.json"

transform:
  simple_transformations:
    dtype_conversion: 
      Estado: "str"
      PK_sigla: "str"
      FK_macro: "str"

    rename_columns: 
      Estado: "nm_uf"
      PK_sigla: "sg_uf"
      geometry: "geometry"
      FK_macro: "regiao"

    transform_columns: 
      regiao: "lambda x: 'Sul' if x=='S' else (
                'Norte' if x=='N' else (
                'Nordeste' if x=='NE' else (
                'Centro-Oeste' if x=='CO' else (
                'Sudeste' if x=='SE' else x))))
                "
vizualize: {}