read:
  url: "https://raw.githubusercontent.com/mapaslivres/municipios-br/main/tabelas/municipios.csv"
  sep: ","
  encoding: "utf-8"

transform:
  simple_transformations:
    dtype_conversion: 
      municipio: "str"
      uf: "str"
      uf_code: "str"

    rename_columns: 
      municipio: "cd_mun"
      uf: "cd_uf"
      uf_code: "sg_uf"