read:
  table_code: 1612
  territorial_level: 6
  variables: [
            "109",  # Área plantada
            "216",  # Área colhida
            "214",  # Quantidade produzida
            "112",  # Rendimento médio
            "215",  # Valor da produção
        ]
  period: ["2019", "2020", "2021"]
  filter_class: {"81": "2713"}
  ibge_territorial_code: "all"
  cache_file: "data/pam_cache.parquet"

transform:
    simple_transformations: 
        dtype_conversion:
            D1C: "str"
            D2N: "str"
            V: "float"

        pivot_table: 
            index: ["D1C", "D2N"]
            columns: "D4N"
            values: "V"

        rename_columns: 
            D1C: "cd_mun"
            D2N: "ano"
            Quantidade produzida: "quantidade_producao_t"
            Rendimento médio da produção: "rendimento_medio_kg_ha"
            Valor da produção: "valor_producao_mil_reais"
            Área colhida: "area_colhida_ha"
            Área plantada: "area_plantada_ha"

        filter_rows: 
            ano: ["2019", "2020", "2021"]
          
    merge:
        output_name: "pam_enriched"
        tables:
            geom_mun: 
                merge_on: ["cd_mun"]
                how: "left"
                suffixes: ["_pam", "_mun"]
            geom_uf: 
                merge_on: ["sg_uf"]
                how: "left"
                suffixes: ["_pam", "_uf"]
            conab: 
                merge_on: ["ano","sg_uf"]
                how: "left"
                suffixes: ["_pam", "_conab"]
                
    groupby:
        dataframe: "pam_enriched"
        output_name: "pam_uf"
        group_cols: ["ano", "regiao" ,"sg_uf"]
        aggregations:
            quantidade_producao_t_pam: "sum"
            rendimento_medio_kg_ha_pam: "mean"
            area_plantada_ha_pam: "sum"
            valor_producao_mil_reais: "sum"
            area_plantada_ha_conab: "first"
            quantidade_producao_t_conab: "first"
            rendimento_medio_kg_ha_conab: "first"
            geometry_uf: "first"
    
    calculate_diff_pam_conab:
        dataframe: "pam_uf"
        output_name: "pam_uf"
        group_cols: ["ano", "regiao", "sg_uf"]
        value_cols:
            area_plantada_ha_pam: "area_plantada_ha_conab"
            quantidade_producao_t_pam: "quantidade_producao_t_conab"
            rendimento_medio_kg_ha_pam: "rendimento_medio_kg_ha_conab"

    calculate_area_productivity_correlation:
        dataframe: "pam_uf"
        output_name: "pam_uf_area_productivity_corr"
        area_col: "area_plantada_ha_pam"
        productivity_col: "rendimento_medio_kg_ha_pam"

    calculate_pct_mun_uf:
        dataframes: ["pam_enriched", "pam_uf"]
        output_name: "pam_enriched_pct"
        join_cols: ["ano", "regiao", "sg_uf"]
        used_cols: [
                    "area_plantada_ha_pam",
                    "quantidade_producao_t_pam",
                    "valor_producao_mil_reais"
                    ]
    calculate_temporal_growth:
        dataframes: ["pam_enriched_pct", "pam_uf"]
        output_name: "growth"
        group_cols: [["regiao", "sg_uf", "cd_mun", "nm_mun"], ["regiao", "sg_uf"]]
        value_cols: ["area_plantada_ha_pam", "quantidade_producao_t_pam", "rendimento_medio_kg_ha_pam", "valor_producao_mil_reais"]
        year_col: "ano"
        base_year: "2019"
        target_year: "2021"

    project_pam_next_year:
        dataframes: ["pam_enriched_pct", "conab"]
        output_name: "pam_projected_2022"
        group_cols: ["sg_uf"]
        level_analysis: "cd_mun"
        value_cols: 
            pct_mun_uf_area_plantada_ha_pam: "area_plantada_ha"
            pct_mun_uf_quantidade_producao_t_pam: "quantidade_producao_t"
                    
        year_col: "ano"
        reference_year: "2021"
        projected_year: "2022"


vizualize:
    plot_divergence_line:
        dataframe: "pam_uf"
        group_cols: [["ano", "regiao"], ["ano", "regiao"]]
        x_cols: ["ano", "ano"]
        y_cols: ["diff_area_plantada_ha_conab_pam", "rate_area_plantada_ha_conab_pam"]
        rate_suffixes: ["pam", "conab"]
        recalculate_rates: [False, True]
        add_straight_line: [[True, 0], [True, 1]]
        analysis_cols: ["regiao", "regiao"]
        titles: ["Divergência entre Área Plantada de Soja Pam e Conab por Região do Brasil",
                "Taxa de Divergência entre Área Plantada de Soja Pam e Conab por Região do Brasil"]
        subtitles: ["Valores negativos indicam que a Pam reportou uma área plantada menor que a Conab",
                    "Valores abaixo de 1 indicam que a Pam reportou uma área plantada menor que a Conab"]
        x_labels: ["Ano", "Ano"]
        y_labels: ["Diferença na Área Plantada (ha)", 
                    "Taxa de Diferença na Área Plantada"]
        output_files: ["plots/divergence_area_plantada_pam_conab.png", 
                        "plots/rate_divergence_area_plantada_pam_conab.png"]

    plot_divergence_scatter:
        dataframes: ["pam_uf", "pam_uf", "growth_pam_uf"]
        group_cols: [["regiao", "sg_uf"], ["regiao", "sg_uf"], ["regiao", "sg_uf"]]
        x_cols: ["area_plantada_ha_pam", "diff_quantidade_producao_t_conab_pam", "growth_area_plantada_ha_pam"]
        y_cols: ["area_plantada_ha_conab", "diff_rendimento_medio_kg_ha_conab_pam", "growth_rendimento_medio_kg_ha_pam"]
        add_straight_line: [true, false, false]
        split_zones: [false, true, true]
        analysis_cols: [["regiao", "sg_uf"], ["regiao", "sg_uf"], ["regiao", "sg_uf"]]
        color_cols: ["regiao", "regiao", "regiao"]
        titles: ["Análise de Área Plantada de Soja - Pam x Conab", 
                "Análise de Rendimento Médio de Soja - Pam x Conab",
                "Crescimento de Área Plantada vs Crescimento de Rendimento Médio de Soja (2019-2021)"]
        subtitles: ["Análise por Unidade Federativa, agregada por Ano",
                    "Análise por Unidade Federativa, agregada por Ano",
                    "Análise por Unidade Federativa entre 2019 e 2021"]
        x_labels: ["Área Plantada PAM (ha)", 
                  "Diferença na Área Plantada (ha)", 
                  "Crescimento na Área Plantada (%)"]
        y_labels: ["Área Plantada CONAB (ha)", 
                  "Diferença no Rendimento Médio (kg/ha)", 
                  "Crescimento no Rendimento Médio (%)"]
        output_files: ["plots/area_uf_divergence_pam_conab.png", 
                      "plots/rendimento_area_uf_divergence_pam_conab.png", 
                      "plots/growth_area_vs_productivity_pam_uf.png"]